
version: "2"
services:
  web:
    build: ./auth_api
    ports:
      - "5000:5000"
    depends_on:
      - db
  web2:
    build: ./base_B_api
    ports:
      - "3000:3000"
    depends_on:
      - db2
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
     - "5432"
  db2:
    image: mongo:3.0.2
    expose:
      - "27017"
    ports:
     - "27017:27017"
networks:
      test_network:
         external: true